name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        source venv/bin/activate
        flake8 src tests --max-line-length=100

    - name: Format check with black (optional)
      run: |
        source venv/bin/activate
        black --check src tests

    - name: Run unit tests
      run: |
        source venv/bin/activate
        python -m unittest discover tests
